import React, { useState, useEffect } from 'react';
import { Eye, Edit2, Trash2, X, CheckCircle2, XCircle, Clock, Send, ChevronRight, AlertCircle, Users, MapPin, Search, Bell, Download, CalendarRange, FileText } from 'lucide-react';
import InsuranceUpload from './InsuranceUpload';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import InvitationForm from './InvitationForm';

const MULTI_DAY_TYPES = [
  'Evangelistic Campaign',
  'Prayer Week',
  'Health Week',
  'Camp Meeting',
  'Youth Seminar',
  'Family Seminar',
  'Leadership Training',
  'Community Outreach',
];

const InvitationFlow = ({ user, token }) => {
  const [invitations, setInvitations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showNewRequest, setShowNewRequest] = useState(false);
  const [viewInvitation, setViewInvitation] = useState(null);
  const [editInvitation, setEditInvitation] = useState(null);

  useEffect(() => { fetchData(); }, []);

  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFillColor(37, 99, 235);
    doc.roundedRect(14, 14, 12, 12, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("PISCS", 15, 21.5);

    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42);
    doc.text("System Operations Report", 32, 23.5);

    doc.setDrawColor(226, 232, 240);
    doc.line(14, 30, pageWidth - 14, 30);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);

    const dateStr = new Date().toLocaleString();
    const systemName = "Preacher Invitation and Service Coordination System";
    const userName = user?.name || user?.email || 'Administrator';

    doc.text(`System Name: ${systemName}`, 14, 40);
    doc.text(`Report Subject: Invitation Queue`, 14, 46);
    doc.text(`Generated By: ${userName}`, 14, 52);
    doc.text(`Date and Time: ${dateStr}`, 14, 58);

    const activeHeaders = ['Ref #', 'Requesting Pastor', 'Invited Speaker', 'Service Date', 'Service Type', 'Priority', 'Status'];
    const activeData = invitations.map(inv => {
      const dateDisplay = inv.service_end_date
        ? `${new Date(inv.service_date).toLocaleDateString('en-GB')} – ${new Date(inv.service_end_date).toLocaleDateString('en-GB')}`
        : new Date(inv.service_date).toLocaleDateString('en-GB');
      return [
        `#${inv.id.toString().padStart(4, '0')}`,
        inv.pastor_name || '—',
        inv.preacher_name || '—',
        dateDisplay,
        inv.service_type || '—',
        inv.priority || 'Medium',
        (inv.status || '').replace(/_/g, ' ').toUpperCase()
      ];
    });

    autoTable(doc, {
      head: [activeHeaders],
      body: activeData,
      startY: 72,
      theme: 'grid',
      styles: { fontSize: 8, font: 'helvetica', cellPadding: 3 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 25, doc.internal.pageSize.getHeight() - 10);
    }

    doc.save(`PISCS_Report_${dateStr.replace(/[\/\\:, ]/g, '_')}.pdf`);
  };

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await fetch('http://localhost:5000/api/invitations', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      const data = await res.json();
      console.log('🔍 RAW API DATA (first record):', data[0]);
      console.log('🔍 CURRENT USER:', user);
      setInvitations(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error('Sync failed:', err);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (id, status, note) => {
    try {
      const res = await fetch(`http://localhost:5000/api/invitations/${id}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify({ status, note })
      });
      if (res.ok) { fetchData(); setViewInvitation(null); }
    } catch (err) { console.error(err); }
  };

  const handleReject = async (id, roleLabel) => {
    const reason = window.prompt(`Please provide a reason for rejecting/declining this mission (#${id}):`);
    if (reason === null) return;
    await updateStatus(id, 'rejected', reason.trim() || `Declined by ${roleLabel}`);
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you certain you want to permanently delete this mission record? This cannot be undone.')) return;
    try {
      const res = await fetch(`http://localhost:5000/api/invitations/${id}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) fetchData();
      else alert('Failed to delete invitation');
    } catch (err) { console.error(err); }
  };

  const handleRemind = async (id) => {
    try {
      const res = await fetch(`http://localhost:5000/api/invitations/${id}/remind`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        alert('Reminder notification sent successfully to the current stakeholder.');
      } else {
        const data = await res.json();
        alert(data.error || 'Failed to send reminder');
      }
    } catch (err) {
      console.error('Remind failed:', err);
    }
  };

  const statusConfig = {
    pending_field1_secretary: { label: 'Awaiting Field 1 Secretary', color: 'bg-amber-100 text-amber-700 border-amber-200', dot: 'bg-amber-400' },
    pending_field2_secretary: { label: 'Awaiting Field 2 Secretary', color: 'bg-blue-100 text-blue-700 border-blue-200', dot: 'bg-blue-400' },
    pending_preacher_confirmation: { label: 'Awaiting Preacher Confirmation', color: 'bg-purple-100 text-purple-700 border-purple-200', dot: 'bg-purple-400' },
    approved: { label: 'Approved', color: 'bg-emerald-100 text-emerald-700 border-emerald-200', dot: 'bg-emerald-400' },
    rejected: { label: 'Rejected', color: 'bg-rose-100 text-rose-700 border-rose-200', dot: 'bg-rose-400' },
    cancelled: { label: 'Cancelled', color: 'bg-slate-100 text-slate-500 border-slate-200', dot: 'bg-slate-400' },
  };

  const StatusBadge = ({ status }) => {
    const cfg = statusConfig[status] || { label: status, color: 'bg-slate-100 text-slate-600 border-slate-200', dot: 'bg-slate-400' };
    return (
      <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-wider border ${cfg.color}`}>
        <span className={`w-1.5 h-1.5 rounded-full ${cfg.dot} animate-pulse`} />
        {cfg.label}
      </span>
    );
  };

  const renderDateDisplay = (inv) => {
    if (inv.service_end_date) {
      return (
        <div>
          <p className="font-bold text-slate-700 text-sm whitespace-nowrap">
            {new Date(inv.service_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
          </p>
          <p className="text-[10px] text-slate-400 font-bold mt-0.5 flex items-center gap-1">
            <CalendarRange className="w-3 h-3" />
            to {new Date(inv.service_end_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
          </p>
        </div>
      );
    }
    return (
      <p className="font-bold text-slate-700 text-sm whitespace-nowrap">
        {new Date(inv.service_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
      </p>
    );
  };

  const canEdit = (inv) => {
    if (user.role === 'admin') return true;
    return (
      user.role === 'pastor' &&
      parseInt(inv.requesting_pastor_id) === parseInt(user.id) &&
      inv.status === 'pending_field1_secretary'
    );
  };

  // FIX: type-safe check for upload condition
  const canUploadInsurance = (inv) =>
    inv.status === 'approved' &&
    user.role === 'pastor' &&
    parseInt(inv.requesting_pastor_id) === parseInt(user.id) &&
    !!inv.target_user_id;

  if (loading) return (
    <div className="p-20 text-center">
      <div className="w-10 h-10 border-4 border-slate-200 border-t-blue-600 rounded-full animate-spin mx-auto mb-4" />
      <p className="text-slate-400 font-black uppercase tracking-widest text-[10px]">Synchronizing Queue...</p>
    </div>
  );

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            {user.role === 'pastor' ? 'My Mission Invitations' : 'Invitation Queue'}
          </h2>
          <p className="text-slate-400 text-xs font-bold uppercase tracking-widest mt-1">
            {invitations.length} total record{invitations.length !== 1 ? 's' : ''}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={exportToPDF}
            className="flex items-center gap-2 px-6 py-3 bg-emerald-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-emerald-700 shadow-lg shadow-emerald-200 transition-all active:scale-95"
          >
            <Download className="w-4 h-4" /> Export PDF
          </button>
          {(user.role === 'pastor' || user.role === 'admin') && (
            <button
              onClick={() => setShowNewRequest(true)}
              className="flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-blue-700 shadow-lg shadow-blue-200 active:scale-95 transition-all"
            >
              <Send className="w-4 h-4" /> New Invitation
            </button>
          )}
        </div>
      </div>

      {/* Table */}
      <div className="bg-white rounded-[2rem] border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200">
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Ref #</th>
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Requesting Pastor</th>
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Invited Speaker</th>
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Service Date</th>
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Service Type</th>
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Priority</th>
                <th className="px-6 py-4 text-left text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Status</th>
                <th className="px-6 py-4 text-right text-[10px] font-black text-slate-400 uppercase tracking-[0.15em] whitespace-nowrap">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {invitations.length === 0 ? (
                <tr>
                  <td colSpan="8" className="px-6 py-20 text-center">
                    <AlertCircle className="w-10 h-10 mx-auto text-slate-200 mb-3" />
                    <p className="text-slate-400 font-black text-xs uppercase tracking-widest">No invitations found</p>
                  </td>
                </tr>
              ) : (
                invitations.map(inv => (
                  <tr key={inv.id} className="hover:bg-slate-50 transition-colors group">
                    <td className="px-6 py-5">
                      <span className="text-xs font-black text-slate-400 bg-slate-100 px-2.5 py-1 rounded-lg">
                        #{inv.id.toString().padStart(4, '0')}
                      </span>
                    </td>
                    <td className="px-6 py-5">
                      <p className="font-black text-slate-800 text-sm leading-tight">{inv.pastor_name || '—'}</p>
                      {inv.is_admin_created === 1 && (
                        <span className="text-[9px] text-blue-500 font-black uppercase tracking-widest bg-blue-50 px-1.5 py-0.5 rounded mt-1 inline-block">Admin Created</span>
                      )}
                    </td>
                    <td className="px-6 py-5">
                      <p className="font-black text-slate-800 text-sm leading-tight">{inv.preacher_name || '—'}</p>
                      {inv.preacher_field_name && (
                        <p className="text-[10px] text-slate-400 font-bold mt-0.5">📍 {inv.preacher_field_name}</p>
                      )}
                    </td>
                    <td className="px-6 py-5">{renderDateDisplay(inv)}</td>
                    <td className="px-6 py-5">
                      <div>
                        <p className="text-sm text-slate-600 font-bold">{inv.service_type || '—'}</p>
                        {MULTI_DAY_TYPES.includes(inv.service_type) && (
                          <span className="text-[9px] text-blue-500 font-black uppercase tracking-widest bg-blue-50 px-1.5 py-0.5 rounded mt-1 inline-flex items-center gap-1">
                            <CalendarRange className="w-2.5 h-2.5" /> Multi-day
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-5">
                      <span className={`text-[10px] font-black uppercase tracking-wider px-2.5 py-1 rounded-lg ${inv.priority === 'High' || inv.priority === 'Urgent'
                          ? 'bg-rose-50 text-rose-600'
                          : inv.priority === 'Low'
                            ? 'bg-slate-50 text-slate-500'
                            : 'bg-amber-50 text-amber-600'
                        }`}>
                        {inv.priority || 'Medium'}
                      </span>
                    </td>
                    <td className="px-6 py-5">
                      <StatusBadge status={inv.status} />
                    </td>
                    <td className="px-6 py-5 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={() => {
                            console.log('🔍 VIEWING INVITATION:', inv);
                            console.log('🔍 pastor_name:', inv.pastor_name);
                            console.log('🔍 requesting_pastor_id:', inv.requesting_pastor_id, typeof inv.requesting_pastor_id);
                            console.log('🔍 user.id:', user.id, typeof user.id);
                            console.log('🔍 target_user_id:', inv.target_user_id, typeof inv.target_user_id);
                            console.log('🔍 status:', inv.status);
                            console.log('🔍 canUploadInsurance:', inv.status === 'approved' && user.role === 'pastor' && parseInt(inv.requesting_pastor_id) === parseInt(user.id) && !!inv.target_user_id);
                            setViewInvitation(inv);
                          }}
                          className="flex items-center gap-1.5 px-3 py-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all border border-transparent hover:border-blue-100"
                        >
                          <Eye className="w-3.5 h-3.5" /> View
                        </button>
                        {canEdit(inv) && (
                          <button
                            onClick={() => setEditInvitation(inv)}
                            className="flex items-center gap-1.5 px-3 py-2 text-slate-400 hover:text-amber-600 hover:bg-amber-50 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all border border-transparent hover:border-amber-100"
                          >
                            <Edit2 className="w-3.5 h-3.5" /> Edit
                          </button>
                        )}
                        {user.role === 'admin' && (
                          <div className="flex gap-2">
                            <button
                              onClick={() => handleRemind(inv.id)}
                              className="flex items-center gap-1.5 px-3 py-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all border border-transparent hover:border-blue-100"
                            >
                              <Bell className="w-3.5 h-3.5" /> Remind
                            </button>
                            <button
                              onClick={() => handleDelete(inv.id)}
                              className="flex items-center gap-1.5 px-3 py-2 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all border border-transparent hover:border-rose-100"
                            >
                              <Trash2 className="w-3.5 h-3.5" /> Delete
                            </button>
                          </div>
                        )}
                        {(user.role === 'admin' || ((user.role === 'pastor' || user.role === 'preacher') &&
                          inv.status === 'pending_preacher_confirmation' &&
                          parseInt(inv.target_user_id) === parseInt(user.id))) && (
                            <>
                              <button
                                onClick={() => updateStatus(inv.id, 'approved', 'Accepted')}
                                className="flex items-center gap-1.5 px-3 py-2 bg-emerald-600 text-white rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-emerald-700 transition-all shadow-md shadow-emerald-100"
                              >
                                <CheckCircle2 className="w-3.5 h-3.5" /> Accept
                              </button>
                              <button
                                onClick={() => handleReject(inv.id, user.role.toUpperCase())}
                                className="flex items-center gap-1.5 px-3 py-2 bg-rose-600 text-white rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-rose-700 transition-all shadow-md shadow-rose-100"
                              >
                                <XCircle className="w-3.5 h-3.5" /> Decline
                              </button>
                            </>
                          )}
                        {(user.role === 'admin' || (user.role === 'secretary' && inv.status === 'pending_field1_secretary')) && (
                          <>
                            <button
                              onClick={() => updateStatus(inv.id, 'pending_field2_secretary', 'Approved by Field 1 Secretary')}
                              className="flex items-center gap-1.5 px-3 py-2 bg-blue-600 text-white rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-blue-700 transition-all"
                            >
                              <CheckCircle2 className="w-3.5 h-3.5" /> Approve
                            </button>
                            <button
                              onClick={() => handleReject(inv.id, 'FIELD 1 SECRETARY')}
                              className="flex items-center gap-1.5 px-3 py-2 bg-rose-100 text-rose-600 rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-rose-200 transition-all"
                            >
                              <XCircle className="w-3.5 h-3.5" /> Reject
                            </button>
                          </>
                        )}
                        {(user.role === 'admin' || (user.role === 'secretary' && inv.status === 'pending_field2_secretary')) && (
                          <>
                            <button
                              onClick={() => updateStatus(inv.id, 'pending_preacher_confirmation', 'Approved by Field 2 Secretary')}
                              className="flex items-center gap-1.5 px-3 py-2 bg-purple-600 text-white rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-purple-700 transition-all"
                            >
                              <CheckCircle2 className="w-3.5 h-3.5" /> Forward
                            </button>
                            <button
                              onClick={() => handleReject(inv.id, 'FIELD 2 SECRETARY')}
                              className="flex items-center gap-1.5 px-3 py-2 bg-rose-100 text-rose-600 rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-rose-200 transition-all"
                            >
                              <XCircle className="w-3.5 h-3.5" /> Reject
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* View Detail Modal */}
      {viewInvitation && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[70] p-4">
          <div className="bg-white rounded-[2rem] shadow-2xl w-full max-w-2xl overflow-hidden animate-in zoom-in-95 duration-300">
            <div className="px-8 py-6 border-b border-slate-100 flex items-center justify-between">
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Invitation Detail</p>
                <h3 className="text-xl font-black text-slate-900 mt-0.5">
                  #{viewInvitation.id.toString().padStart(4, '0')} — {viewInvitation.service_type}
                </h3>
              </div>
              <button onClick={() => setViewInvitation(null)} className="p-2 hover:bg-slate-100 rounded-xl transition-colors">
                <X className="w-5 h-5 text-slate-400" />
              </button>
            </div>

            <div className="p-8 space-y-6 max-h-[80vh] overflow-y-auto">

              {/* Pastor Creator — shows pastor_name from the JOIN */}
              <div className="p-4 bg-gray-50 rounded-2xl border border-gray-200">
                <p className="text-[9px] text-slate-400 font-black uppercase tracking-widest mb-1">Invitation Created By</p>
                <p className="text-sm font-black text-slate-800">{viewInvitation.pastor_name || '—'}</p>
              </div>

              <div className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl">
                <span className="text-xs font-black text-slate-500 uppercase tracking-widest">Current Status</span>
                <StatusBadge status={viewInvitation.status} />
              </div>

              <div className="grid grid-cols-2 gap-4">
                {[
                  { label: 'Requesting Pastor', value: viewInvitation.pastor_name },
                  { label: 'Invited Speaker', value: viewInvitation.preacher_name },
                  { label: 'Requester Field', value: viewInvitation.requester_field_name },
                  { label: "Speaker's Field", value: viewInvitation.preacher_field_name },
                  { label: 'Service Type', value: viewInvitation.service_type },
                  { label: 'Priority', value: viewInvitation.priority || 'Medium' },
                ].map(({ label, value }) => (
                  <div key={label} className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                    <p className="text-[9px] text-slate-400 font-black uppercase tracking-widest mb-1">{label}</p>
                    <p className="text-sm font-black text-slate-800">{value || '—'}</p>
                  </div>
                ))}

                {/* Date — full width if multi-day */}
                <div className={`p-4 bg-slate-50 rounded-2xl border border-slate-100 ${viewInvitation.service_end_date ? 'col-span-2' : ''}`}>
                  <p className="text-[9px] text-slate-400 font-black uppercase tracking-widest mb-1 flex items-center gap-1">
                    {viewInvitation.service_end_date ? <CalendarRange className="w-3 h-3" /> : null}
                    {viewInvitation.service_end_date ? 'Event Period' : 'Service Date'}
                  </p>
                  {viewInvitation.service_end_date ? (
                    <div className="flex items-center gap-3">
                      <div>
                        <p className="text-[9px] text-slate-400 font-bold uppercase">Start</p>
                        <p className="text-sm font-black text-slate-800">
                          {new Date(viewInvitation.service_date).toLocaleDateString('en-GB', { weekday: 'short', year: 'numeric', month: 'long', day: 'numeric' })}
                        </p>
                      </div>
                      <ChevronRight className="w-4 h-4 text-slate-300 flex-shrink-0" />
                      <div>
                        <p className="text-[9px] text-slate-400 font-bold uppercase">End</p>
                        <p className="text-sm font-black text-slate-800">
                          {new Date(viewInvitation.service_end_date).toLocaleDateString('en-GB', { weekday: 'short', year: 'numeric', month: 'long', day: 'numeric' })}
                        </p>
                      </div>
                      <div className="ml-auto px-3 py-1 bg-blue-50 border border-blue-100 rounded-xl">
                        <p className="text-[10px] text-blue-600 font-black uppercase tracking-widest">
                          {Math.round((new Date(viewInvitation.service_end_date) - new Date(viewInvitation.service_date)) / (1000 * 60 * 60 * 24)) + 1} days
                        </p>
                      </div>
                    </div>
                  ) : (
                    <p className="text-sm font-black text-slate-800">
                      {new Date(viewInvitation.service_date).toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                    </p>
                  )}
                </div>
              </div>

              {/* Secretary Info */}
              <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-blue-50/50 rounded-2xl border border-blue-100">
                  <p className="text-[9px] text-blue-500 font-black uppercase tracking-widest mb-2">Requesting Field Secretary</p>
                  {viewInvitation.requester_secretary_name ? (
                    <div className="space-y-1">
                      <p className="text-sm font-black text-slate-900">{viewInvitation.requester_secretary_name}</p>
                      <p className="text-[10px] text-slate-500 font-medium">{viewInvitation.requester_secretary_email}</p>
                      <p className="text-[10px] text-slate-500 font-medium">{viewInvitation.requester_secretary_phone}</p>
                    </div>
                  ) : <p className="text-xs text-slate-400 italic">No secretary assigned</p>}
                </div>
                <div className="p-4 bg-indigo-50/50 rounded-2xl border border-indigo-100">
                  <p className="text-[9px] text-indigo-500 font-black uppercase tracking-widest mb-2">Invited Field Secretary</p>
                  {viewInvitation.target_secretary_name ? (
                    <div className="space-y-1">
                      <p className="text-sm font-black text-slate-900">{viewInvitation.target_secretary_name}</p>
                      <p className="text-[10px] text-slate-500 font-medium">{viewInvitation.target_secretary_email}</p>
                      <p className="text-[10px] text-slate-500 font-medium">{viewInvitation.target_secretary_phone}</p>
                    </div>
                  ) : <p className="text-xs text-slate-400 italic">No secretary assigned</p>}
                </div>
              </div>

              {/* Attachment */}
              {viewInvitation.attachment_url && (
                <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-100 flex items-center justify-between group">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center text-emerald-600 shadow-sm group-hover:scale-110 transition-transform">
                      <FileText className="w-5 h-5" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-[9px] text-emerald-500 font-black uppercase tracking-widest">Mission Attachment</p>
                      <p className="text-xs font-black text-slate-700 truncate">Official Program Details</p>
                    </div>
                  </div>
                  <a
                    href={`http://localhost:5000${viewInvitation.attachment_url}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-700 transition-all shadow-md shadow-emerald-200"
                  >
                    <Download className="w-3.5 h-3.5" /> Download
                  </a>
                </div>
              )}

              {/* Notes */}
              {viewInvitation.pastor_note && (
                <div className="p-4 bg-blue-50 rounded-2xl border border-blue-100">
                  <p className="text-[9px] text-blue-400 font-black uppercase tracking-widest mb-2">Pastor's Request Note</p>
                  <p className="text-sm text-blue-800 italic">"{viewInvitation.pastor_note}"</p>
                </div>
              )}

              {/* ── Insurance Upload — FIX: parentheses + parseInt comparison ── */}
              {canUploadInsurance(viewInvitation) ? (
                <InsuranceUpload
                  invitationId={viewInvitation.id}
                  preacherId={viewInvitation.target_user_id}
                  preacherName={viewInvitation.preacher_name}
                  onUploadSuccess={fetchData}
                />
              ) : (
                viewInvitation.status === 'approved' && user.role === 'pastor' && (
                  <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                    <p className="text-xs text-slate-400 font-bold">
                      Insurance upload is only available to the pastor who created this invitation.
                    </p>
                  </div>
                )
              )}

              {viewInvitation.field1_secretary_note && (
                <div className="p-4 bg-amber-50 rounded-2xl border border-amber-100">
                  <p className="text-[9px] text-amber-500 font-black uppercase tracking-widest mb-2">Field 1 Secretary Note</p>
                  <p className="text-sm text-amber-800">{viewInvitation.field1_secretary_note}</p>
                </div>
              )}
              {viewInvitation.field2_secretary_note && (
                <div className="p-4 bg-purple-50 rounded-2xl border border-purple-100">
                  <p className="text-[9px] text-purple-500 font-black uppercase tracking-widest mb-2">Field 2 Secretary Note</p>
                  <p className="text-sm text-purple-800">{viewInvitation.field2_secretary_note}</p>
                </div>
              )}

              {/* Quick actions — preacher accept/decline */}
              {(user.role === 'admin' || ((user.role === 'pastor' || user.role === 'preacher') &&
                viewInvitation.status === 'pending_preacher_confirmation' &&
                parseInt(viewInvitation.target_user_id) === parseInt(user.id))) && (
                  <div className="flex gap-3 pt-2 border-t border-slate-100">
                    <button
                      onClick={() => updateStatus(viewInvitation.id, 'approved', 'Accepted')}
                      className="flex-1 py-3.5 bg-emerald-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-emerald-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-emerald-100"
                    >
                      <CheckCircle2 className="w-4 h-4" /> Accept This Call
                    </button>
                    <button
                      onClick={() => handleReject(viewInvitation.id, user.role.toUpperCase())}
                      className="flex-1 py-3.5 bg-rose-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-rose-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-rose-100"
                    >
                      <XCircle className="w-4 h-4" /> Decline
                    </button>
                  </div>
                )}

              {/* Quick actions — pastor cancel */}
              {user.role === 'pastor' &&
                parseInt(viewInvitation.requesting_pastor_id) === parseInt(user.id) &&
                viewInvitation.status === 'pending_field1_secretary' && (
                  <div className="pt-2 border-t border-slate-100">
                    <button
                      onClick={() => updateStatus(viewInvitation.id, 'cancelled', 'Cancelled by pastor')}
                      className="w-full py-3 border-2 border-rose-200 text-rose-500 rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-rose-50 transition-all"
                    >
                      Cancel This Invitation
                    </button>
                  </div>
                )}
            </div>
          </div>
        </div>
      )}

      {/* New Invitation Modal */}
      {showNewRequest && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-md flex items-center justify-center z-[60] p-4">
          <InvitationForm
            user={user}
            token={token}
            onCancel={() => setShowNewRequest(false)}
            onSuccess={() => { setShowNewRequest(false); fetchData(); }}
          />
        </div>
      )}

      {/* Edit Invitation Modal */}
      {editInvitation && (
        <EditInvitationModal
          invitation={editInvitation}
          user={user}
          token={token}
          onClose={() => setEditInvitation(null)}
          onSaved={() => { setEditInvitation(null); fetchData(); }}
        />
      )}
    </div>
  );
};

/* ── Edit Modal ─────────────────────────────────────────────────────────── */
const EditInvitationModal = ({ invitation, token, onClose, onSaved, user }) => {
  const [form, setForm] = useState({
    service_date: invitation.service_date?.split('T')[0] || '',
    service_end_date: invitation.service_end_date?.split('T')[0] || '',
    service_type: invitation.service_type || '',
    priority: invitation.priority || 'Medium',
    pastor_note: invitation.pastor_note || '',
    requesting_pastor_id: invitation.requesting_pastor_id,
    target_user_id: invitation.target_user_id,
  });
  const [pastors, setPastors] = useState([]);
  const [loadingPastors, setLoadingPastors] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const isMultiDay = MULTI_DAY_TYPES.includes(form.service_type);

  useEffect(() => {
    if (!isMultiDay) {
      setForm(prev => ({ ...prev, service_end_date: '' }));
    }
  }, [form.service_type]);

  const durationDays = isMultiDay && form.service_date && form.service_end_date
    ? Math.round((new Date(form.service_end_date) - new Date(form.service_date)) / (1000 * 60 * 60 * 24)) + 1
    : null;

  useEffect(() => { fetchPastors(); }, []);

  const fetchPastors = async () => {
    setLoadingPastors(true);
    try {
      const res = await fetch('http://localhost:5000/api/directory/pastors', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      const data = await res.json();
      setPastors(Array.isArray(data) ? data : []);
    } catch { }
    finally { setLoadingPastors(false); }
  };

  const getPastorDetails = (id) => pastors.find(p => p.id === parseInt(id)) || {};
  const selectedRequester = getPastorDetails(form.requesting_pastor_id);
  const selectedTarget = getPastorDetails(form.target_user_id);

  const handleSave = async (e) => {
    e.preventDefault();
    if (isMultiDay && form.service_end_date && form.service_end_date < form.service_date) {
      setError('End date cannot be before the start date.');
      return;
    }
    setSaving(true);
    setError('');
    try {
      const payload = {
        ...form,
        service_end_date: isMultiDay ? (form.service_end_date || null) : null,
      };
      const res = await fetch(`http://localhost:5000/api/invitations/${invitation.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (res.ok) { onSaved(); }
      else { setError(data.error || 'Update failed'); }
    } catch { setError('Network error. Please try again.'); }
    finally { setSaving(false); }
  };

  const singleDayTypes = ['Sabbath Service', 'Midweek Service', 'Baptism Service', 'Harvest Festival'];

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[70] p-4">
      <div className="bg-white rounded-[2rem] shadow-2xl w-full max-w-lg overflow-hidden animate-in zoom-in-95 duration-300">
        <div className="px-8 py-6 border-b border-slate-100 flex items-center justify-between">
          <div>
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Edit Invitation</p>
            <h3 className="text-xl font-black text-slate-900 mt-0.5">
              #{invitation.id.toString().padStart(4, '0')} — {invitation.preacher_name}
            </h3>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-100 rounded-xl transition-colors">
            <X className="w-5 h-5 text-slate-400" />
          </button>
        </div>

        <div className="max-h-[80vh] overflow-y-auto">
          <div className="p-8 space-y-6">
            {/* Context panel */}
            <div className="p-6 bg-slate-50 rounded-3xl border border-slate-200">
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Mission Information Context</p>
              <div className="grid grid-cols-2 gap-8">
                <div className="space-y-4">
                  <div className="p-4 bg-white rounded-2xl border border-slate-100 shadow-sm">
                    <label className="text-[9px] text-slate-400 font-black uppercase tracking-widest mb-2 block">Requesting Pastor</label>
                    {user.role === 'admin' ? (
                      <select
                        className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-sm font-black text-slate-900 outline-none focus:border-blue-500 transition-all cursor-pointer"
                        value={form.requesting_pastor_id}
                        onChange={e => setForm({ ...form, requesting_pastor_id: e.target.value })}
                      >
                        {pastors.filter(p => p.role === 'pastor').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                      </select>
                    ) : (
                      <p className="text-sm font-black text-slate-900">{invitation.pastor_name}</p>
                    )}
                    <p className="text-[11px] text-blue-600 font-bold mt-2">
                      📍 {selectedRequester.field_name || invitation.requester_field_name || 'No Field Found'}
                    </p>
                  </div>
                  <div className="p-4 bg-blue-50/50 rounded-2xl border border-blue-100">
                    <p className="text-[9px] text-blue-500 font-black uppercase tracking-widest mb-2">Requester's Secretary</p>
                    <p className="text-xs font-black text-slate-700">{invitation.requester_secretary_name || 'N/A'}</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div className="p-4 bg-white rounded-2xl border border-slate-100 shadow-sm">
                    <label className="text-[9px] text-slate-400 font-black uppercase tracking-widest mb-2 block">Invited Speaker</label>
                    {(user.role === 'admin' || (user.role === 'pastor' && invitation.status === 'pending_field1_secretary')) ? (
                      <select
                        className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-sm font-black text-slate-900 outline-none focus:border-indigo-500 transition-all cursor-pointer"
                        value={form.target_user_id}
                        onChange={e => setForm({ ...form, target_user_id: e.target.value })}
                      >
                        {pastors.filter(p => p.role === 'preacher').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                      </select>
                    ) : (
                      <p className="text-sm font-black text-slate-900">{invitation.preacher_name}</p>
                    )}
                    <p className="text-[11px] text-indigo-600 font-bold mt-2">
                      📍 {selectedTarget.field_name || invitation.preacher_field_name || 'No Field Found'}
                    </p>
                  </div>
                  <div className="p-4 bg-indigo-50/50 rounded-2xl border border-indigo-100">
                    <p className="text-[9px] text-indigo-500 font-black uppercase tracking-widest mb-2">Speaker's Secretary</p>
                    <p className="text-xs font-black text-slate-700">{invitation.target_secretary_name || 'N/A'}</p>
                  </div>
                </div>
              </div>
            </div>

            <form onSubmit={handleSave} className="space-y-6">
              {error && (
                <div className="p-4 bg-rose-50 border border-rose-200 rounded-2xl text-xs text-rose-600 font-bold">{error}</div>
              )}

              {/* Service Type */}
              <div className="space-y-2">
                <label className="text-xs font-black text-slate-700 uppercase tracking-widest">Service Type</label>
                <select
                  className="w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-5 py-3.5 text-sm font-bold text-slate-900 outline-none focus:border-blue-500 transition-all"
                  value={form.service_type}
                  onChange={e => setForm({ ...form, service_type: e.target.value })}
                  required
                >
                  <optgroup label="Single Day">
                    {singleDayTypes.map(t => <option key={t} value={t}>{t}</option>)}
                  </optgroup>
                  <optgroup label="Multi-Day Event">
                    {MULTI_DAY_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                  </optgroup>
                </select>
                {isMultiDay && (
                  <div className="flex items-center gap-2 px-4 py-2 bg-blue-50 border border-blue-100 rounded-xl animate-in slide-in-from-top-2 duration-300">
                    <CalendarRange className="w-3.5 h-3.5 text-blue-500 flex-shrink-0" />
                    <p className="text-[10px] text-blue-600 font-black uppercase tracking-widest">Multi-day event — set start and end date</p>
                  </div>
                )}
              </div>

              {/* Date fields */}
              {isMultiDay ? (
                <div className="space-y-3">
                  <label className="text-xs font-black text-slate-700 uppercase tracking-widest flex items-center gap-2">
                    <CalendarRange className="w-4 h-4 text-slate-400" /> Event Period
                  </label>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Start Date</p>
                      <input
                        type="date"
                        className="w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-5 py-3.5 text-sm font-bold text-slate-900 outline-none focus:border-blue-500 transition-all"
                        value={form.service_date}
                        onChange={e => setForm({ ...form, service_date: e.target.value })}
                        required
                      />
                    </div>
                    <div className="space-y-1">
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">End Date</p>
                      <input
                        type="date"
                        className="w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-5 py-3.5 text-sm font-bold text-slate-900 outline-none focus:border-blue-500 transition-all"
                        value={form.service_end_date}
                        min={form.service_date || undefined}
                        onChange={e => setForm({ ...form, service_end_date: e.target.value })}
                      />
                    </div>
                  </div>
                  {durationDays !== null && durationDays > 0 && (
                    <div className="flex items-center gap-2 px-4 py-2 bg-emerald-50 border border-emerald-100 rounded-xl animate-in slide-in-from-top-2 duration-200">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 flex-shrink-0" />
                      <p className="text-[10px] text-emerald-700 font-black uppercase tracking-widest">
                        Duration: {durationDays} {durationDays === 1 ? 'day' : 'days'}
                      </p>
                    </div>
                  )}
                </div>
              ) : (
                <div className="space-y-2">
                  <label className="text-xs font-black text-slate-700 uppercase tracking-widest">Service Date</label>
                  <input
                    type="date"
                    className="w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-5 py-3.5 text-sm font-bold text-slate-900 outline-none focus:border-blue-500 transition-all"
                    value={form.service_date}
                    onChange={e => setForm({ ...form, service_date: e.target.value })}
                    required
                  />
                </div>
              )}

              {/* Priority */}
              <div className="space-y-2">
                <label className="text-xs font-black text-slate-700 uppercase tracking-widest">Priority</label>
                <div className="flex gap-2 p-1.5 bg-slate-50 rounded-2xl border border-slate-100">
                  {['Low', 'Medium', 'High', 'Urgent'].map(p => (
                    <button key={p} type="button"
                      onClick={() => setForm({ ...form, priority: p })}
                      className={`flex-1 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-wider transition-all ${form.priority === p ? 'bg-white shadow text-slate-900' : 'text-slate-400 hover:text-slate-600'
                        }`}>
                      {p}
                    </button>
                  ))}
                </div>
              </div>

              {/* Note */}
              <div className="space-y-2">
                <label className="text-xs font-black text-slate-700 uppercase tracking-widest">Coordination Notes</label>
                <textarea
                  className="w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-5 py-4 text-sm text-slate-700 outline-none focus:border-blue-500 transition-all min-h-[100px] resize-none"
                  placeholder="Explain the purpose of this invitation..."
                  value={form.pastor_note}
                  onChange={e => setForm({ ...form, pastor_note: e.target.value })}
                />
              </div>

              <div className="flex gap-3 pt-2">
                <button type="button" onClick={onClose}
                  className="px-6 py-3 text-slate-400 font-bold text-xs uppercase tracking-widest hover:text-slate-600 transition-colors">
                  Cancel
                </button>
                <button type="submit" disabled={saving}
                  className="flex-1 py-3.5 bg-blue-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-blue-700 transition-all shadow-lg shadow-blue-100 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2">
                  {saving ? 'Updating...' : <><Edit2 className="w-4 h-4" /> Update Record</>}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default InvitationFlow;